#
# ==== General info ====
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false

#
# Enable main features. Possible values: true | false (default = false)
#
enabled: true

#
# List of max health multipliers for sequential deaths.
#
# The 1.0 multiplier means the player max health won't be changed.
#
# Each multiplier has to be a float value starting from 0.0001.
#

levels:
  - 1.0
  - 0.7
  - 0.5
  - 0.3
  - 0.2
  - 0.1
  - 0.05

#
# Time required for a player to be alive to recover to the previous level, in game time.
#
# Possible values: hour | day | week
#
recovery-survival-period: day

#
# Kill required for a player to recover to the previous level.
#
# Value has to be a integer value starting from 1.
#
recovery-mob-kills: 10